### ISSUE TITLE
Any plans to support 0x v2?

### ISSUE THREAD

**Issue by alejoloaiza** [linki/0x-go#17]
Hi, Any plans to support 0x v2?

**Comment by linki** [comment]
@alejoloaiza I started porting the CLI parts over to v2: https://github.com/linki/0x-go/pull/19

**Comment by linki** [comment]
Slowly progressing. I removed the contract related code of the v1 version, e.g. filling orders, when merging the v2 branch. Now, the project is merely an API client to a relayer which can sign and validate orders.
